#!/bin/sh
get_secret () {
    VAR_NAME="${1}"
    GIVEN_PATH="${2}"

    if [ -e ${GIVEN_PATH} ]; then
        export ${VAR_NAME}="$(cat ${GIVEN_PATH})"
    fi
}

get_secret "DISCORD_TOKEN" "~/.discordtoken"
get_secret "DISCORD_GUILD" "~/.discordguild"
get_secret "YOUTUBE_API_KEY" "~/.youtubeapikey"
get_secret "CLIENT_SECRET_PATH" "~/.clientsecretpath"
get_secret "OPENAI_API_KEY" "~/.openaikey";
get_secret "WOLFRAM_TOKEN" "~/.wolframtoken";
get_secret "SLACK_APP_TOKEN" "~/.slackapptoken";
get_secret "SLACK_BOT_TOKEN" "~/.slackbottoken";

if [ "${STAMPY_RUN_TESTS:-nil}" != "nil" ]; then
    pytest;
    python -m unittest;
    mypy -m stam;
else
    while true; do
        python stam.py ;
        sleep 0.5;
    done
fi

# also run CommentPoster.py
