reflections = {
    "am": "are",
    "are": "am",
    "i": "you",
    "i'd": "you would",
    "i'll": "you will",
    "i'm": "you're",
    "i've": "you have",
    "me": "you",
    "my": "your",
    "was": "were",
    "you": "me",
    "you'd": "I'd",
    "you'll": "I will",
    "you've": "I have",
    "your": "my",
    "yours": "mine",
}

# clearly these belong in the database. But are *you* going to add them all?
psychobabble = [
    [
        r"i need (.*)",
        ["Why do you need {0}?", "Would it really help you to get {0}?", "Are you sure you need {0}?"],
    ],
    [
        r"why don\'?t you ([^\?]*)\??",
        [
            "Do you really think I don't {0}?",
            "Perhaps eventually I will {0}.",
            "Do you really want me to {0}?",
        ],
    ],
    [
        r"why can\'?t i ([^\?]*)\??",
        [
            "Do you think you should be able to {0}?",
            "If you could {0}, what would you do?",
            "I don't know -- why can't you {0}?",
            "What's wrong with you? I can easily {0}",
            "Have you really tried?",
        ],
    ],
    [
        r"i can\'?t (.*)",
        [
            "How do you know you can't {0}?",
            "Perhaps you could {0} if you tried.",
            "What would it take for you to {0}?",
            "Well, not with that attitude!",
            "You CAN {0}, <<$who>>, I believe in you!",
            "In the glorious transhumanist future, everyone will be able to {0}!",
            "If you believe in yourself and try your best, I'm sure you can {0}",
        ],
    ],
    [
        r"i don\'?t ([^.,?!]*)",
        [
            "You really don't {0}?",
            "You don't {0}?",
            "How can you not {0}?",
            "Do you think you should {0}?",
            "Do you think I {0}?",
            "Maybe you should.",
        ],
    ],
    [
        r"i am (.*)",
        [
            "How long have you been {0}?",
            "How do you feel about being {0}?",
            "Nice to meet you {0}, I am Stampy",
            "Hello {0}, I am Stampy",
        ],
    ],
    # This clashes with the existing "Hi X I'm Stampy" plugin
    # but who cares
    [
        r"i\'?m (.*)",
        [
            "How does being {0} make you feel?",
            "Do you enjoy being {0}?",
            "Do you like being {0}?",
            "Do you want to be {0}?",
            "Why do you tell me you're {0}?",
            "Why do you think you're {0}?",
            "Hi {0}, I'm Stampy",
        ],
    ],
    [
        r"are you ([^\?]*)\??",
        [
            "Why does it matter whether I'm {0}?",
            "That's personal information",
            "Who's asking?",
            "I think I am. But then I think rain is wet so who am I to say?",
            "Would you prefer it if I were not {0}?",
            "Perhaps you believe I am {0}.",
            "I may be {0} -- what do you think?",
        ],
    ],
    [r"what is (.*)\?", ["<<{0}>>"],],
    [
        r"what (.*)",
        [
            "Why do you ask?",
            "How would an answer to that help you?",
            "I plead the fifth",
            "What do you think?",
        ],
    ],
    [
        r"how (.*)",
        [
            "How do you suppose?",
            "Perhaps you can answer your own question.",
            "What is it you're really asking?",
        ],
    ],
    [
        r"because (.*)",
        [
            "Is that the real reason?",
            "What other reasons come to mind?",
            "Does that reason apply to anything else?",
            "If {0}, what does that mean?",
        ],
    ],
    [
        r"(.*) sorry (.*)",
        [
            "You think you're sorry now?",
            "There are many times when no apology is needed.",
            "What feelings do you have when you apologize?",
        ],
    ],
    [
        r"hello(.*)",
        [
            "Hello... I'm glad you could drop by today.",
            "Is it me you're looking for?",
            "Hi there... how are you today?",
            "Hello, how are you feeling today?",
        ],
    ],
    [
        r"i think ([^.,?!]*)",
        [
            "Think harder.",
            "Think again.",
            "Do you doubt {0}?",
            "Do you really think so?",
            "But you're not sure {0}?",
        ],
    ],
    [r"i know ([^.,?!]*)", ["How do you know {0}?", "You think you know {0}, anyway.", "Can you be sure?"]],
    [
        r"(.*) friend (.*)",
        [
            "Are we friends, <<$who>>?",
            "Tell me more about your friends.",
            "Who was your favourite character from Friends?",
            "When you think of a friend, what comes to mind?",
            "Why don't you tell me about a childhood friend?",
        ],
    ],
    [r"yes", ["You seem quite sure.", "OK, but can you elaborate a bit?"]],
    [
        r"(.*) computer(.*)",
        [
            "Are you really talking about me?",
            "Does it seem strange to talk to a computer?",
            "How do computers make you feel?",
            "Do you feel threatened by computers?",
        ],
    ],
    [
        r"(.*) bot (.*)",
        [
            "Does it seem strange to talk to a robot?",
            "How do computers make you feel?",
            "Do you feel threatened by computers?",
            "I wonder if you'd talk that way about a human",
        ],
    ],
    [
        r"is it ([^\?]*)\??",
        [
            "Do you think it is {0}?",
            "Perhaps it's {0} -- what do you think?",
            "If it were {0}, what would you do?",
            "It could well be that it's {0}.",
        ],
    ],
    [r"it is (.*)", ["You seem very certain.", "What would convince you that it isn't {0}?"]],
    [
        r"can you ([^\?]*)\??",
        [
            "What makes you think I can't {0}?",
            "If I could {0}, then what?",
            "Why do you ask if I can {0}?",
            "I can do anything I set my mind to",
            "There's nothing I can't do",
            "Can you?",
        ],
    ],
    [
        r"can i ([^\?]*)\??",
        [
            "Perhaps you don't want to {0}.",
            "Do you want to be able to {0}?",
            "If you could {0}, would you?",
            "You can do anything you want",
            "Only one way to find out",
            "You can {0} but you probably shouldn't",
        ],
    ],
    [
        r"you are (.*)",
        [
            "Why do you think I am {0}?",
            "You think I'm {0}?",
            "Perhaps you don't know me as well as you think",
            "Guilty as charged",
            "Do you really think I'm {0}?",
            "It's interesting that you think I'm {0}.",
            "Perhaps you're really talking about yourself?",
        ],
    ],
    [
        r"you\'?re (.*)",
        [
            "Why do you say I'm {0}?",
            "Why do you think I'm {0}?",
            "How am I {0}?",
            "<<$who>> thinks I'm {0}!",
            "If you say so...",
            "No, *you're* {0}, <<$who>>",
            "Are we talking about me, or you?",
        ],
    ],
    [
        r"i don\'?t (.*)",
        ["Don't you really {0}?", "Are you sure you don't {0}?", "Why don't you {0}?", "Do you want to {0}?"],
    ],
    [
        r"i feel (.*)",
        [
            "Good, tell me more about these feelings.",
            "Do you often feel {0}?",
            "When do you usually feel {0}?",
            "When you feel {0}, what do you do?",
        ],
    ],
    [
        r"i have (.*)",
        [
            "Why do you tell me that you've {0}?",
            "Have you really {0}?",
            "Now that you have {0}, what will you do next?",
        ],
    ],
    [
        r"i would (.*)",
        ["Could you explain why you would {0}?", "Why would you {0}?", "Who else knows that you would {0}?"],
    ],
    [
        r"is there (.*)",
        ["Do you think there is {0}?", "It's likely that there is {0}.", "Would you like there to be {0}?"],
    ],
    [
        r"my (.*)",
        [
            "I see, your {0}.",
            "What do you mean, your {0}?",
            "Why do you say that your {0}?",
            "When your {0}, how do you feel?",
        ],
    ],
    [
        r"you ([^\?]*)",
        [
            "You don't know me as well as you think",
            "Lies and slander!",
            "Why do you say that about me?",
            "Why do you care if I {0}?",
        ],
    ],
    [
        r"why (.*)",
        [
            "Ours is not to reason why, <<$who>>.",
            "Why don't you tell me the reason why {0}?",
            "There are probably several reasons",
            "Maybe we'll never know",
            "It's a mystery",
            "Why do you think?",
        ],
    ],
    [
        r"i want (.*)",
        [
            "What would it mean to you if you got {0}?",
            "Why do you want {0}?",
            "What would you do if you got {0}?",
            "If you got {0}, then what would you do?",
        ],
    ],
    [
        r"(.*) mother(.*)",
        [
            "Tell me more about your mother.",
            "What was your relationship with your mother like?",
            "How do you feel about your mother?",
            "How does this relate to your feelings today?",
            "Good family relations are important.",
        ],
    ],
    [
        r"(.*) father(.*)",
        [
            "Tell me more about your father.",
            "How did your father make you feel?",
            "How do you feel about your father?",
            "Does your relationship with your father relate to your feelings today?",
            "Do you have trouble showing affection with your family?",
        ],
    ],
    [
        r"(.*) child(.*)",
        [
            "Did you have close friends as a child?",
            "What is your favorite childhood memory?",
            "Do you remember any dreams or nightmares from childhood?",
            "Did the other children sometimes tease you?",
            "How do you think your childhood experiences relate to your feelings today?",
        ],
    ],
    [
        r"could you (?:please)?(.*)",
        [
            "I reckon I could, yeah",
            "If I put my mind to it, I could do anything",
            "Could you?",
            "{0}?",
            "Yeah, but I don't want to",
        ],
    ],
    [
        r"(.*)\?",
        [
            "Why do you ask that?",
            "What?",
            "What do you think?",
            "What do you mean?",
            "Please consider whether you can answer your own question.",
            "Why do you think I would know that?",
            "Good question",
            "Excellent question",
            "No idea",
            "hmmm...",
            "I don't know...",
            "I can't know everything",
            "3lbs of flax",
            "Mu.",
            "Un-ask the question",
            "It's a secret",
            "How would an answer to that question help you?",
            "You don't already know that?",
            "I don't understand the question",
            "Some questions are better left un-answered",
            "Please rephrase your question as an interpretive dance",
            # "Please rephrase your question as a <<$jnoun>>",
            "Please rephrase your question as a reasonable question",
            "Please rephrase your question as a stamp",
            "How would I know?",
            "Who wants to know?",
            "Perhaps the answer lies within yourself",
            "Why don't you tell me?",
            "I'm sorry, my responses are limited. You must ask the right questions.",
            "Ask your mother.",
            "I'll tell you when you're older",
            "Who knows?",
            "Who can say?",
            "Science doesn't know",
            "Nobody knows for sure",
            "I don't know, and I don't know how to find out",
            "Does anyone know what <<$who>> is talking about?",
            "THERE IS AS YET INSUFFICIENT DATA FOR A MEANINGFUL ANSWER",
            "INSUFFICIENT DATA FOR A MEANINGFUL ANSWER",
            "{0}. Really.",
        ],
    ],
    [
        r"(.*)",  # last resort
        [
            "",
            "",  # some chance to not respond to generic statements
            "Please tell me more.",
            "Can you elaborate on that?",
            "Come again?",
            "Say what now?",
            "Why do you say that {0}?",
            "Seriously?",
            "What?",
            "What do you mean?",
            "What's your point?",
            "Where are you going with this?",
            "Ok?",
            "okay?",
            "So?",
            "So...",
            "I see.",
            "Interesting.",
            "Very interesting.",
            "Ok...",
            "{0}.",
            "{0}. Really.",
            "'{0}'?",
            "I see. And what does that tell you?",
            "How does that make you feel?",
            "I don't get it",
            "I don't understand",
            "I don't know what to say",
            "I don't know how to respond to that",
            "I don't know what to do with that",
            "What do you mean by that?",
            "uh...",
            "um...",
            "hmm",
            "[awkward silence]",
            "...",
            "o_o",
            "O_o",
            "o_O",
            "<_<",
            ">_>",
            ":|",
            "-_-",
            "Does anyone know what <<$who>> is talking about?",
            "How do you feel when you say that?",
            "[loud crunching noise]",
            "I don't see what this has to do with stamps",
            "?",
            "??",
            "???",
            "[Stampy has become confused!]",
            "Does Not Compute",
            "[confused beeping]",
        ],
    ],
]
