name: Test
on:
  - push
  - pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stampy to Development Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_DEV_HOST}}
          key: ${{secrets.SSH_DEV_KEY}}
          username: ${{secrets.SSH_DEV_USERNAME}}
          script: |
            source ~/.zshrc
            source ~/stampy/scripts/update-stampy.sh
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0